name: Deployment to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push to ECR
        run: |
          docker tag sgroup-devops:latest 524387458597.dkr.ecr.us-east-1.amazonaws.com/sgroup-devops:latest
          docker push 524387458597.dkr.ecr.us-east-1.amazonaws.com/sgroup-devops:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY}}
          script: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 524387458597.dkr.ecr.us-east-1.amazonaws.com
            docker pull 524387458597.dkr.ecr.us-east-1.amazonaws.com/sgroup-devops:latest
            docker stop sgroup-devops-container || true
            docker rm sgroup-devops-container || true
            docker run -d --name sgroup-devops-container -p 3000:3000 -e DATABASE_URL=mongodb+srv://nguyencongtrinhqb:sgroup123@cluster0.qom7v1f.mongodb.net/sgroup 524387458597.dkr.ecr.us-east-1.amazonaws.com/sgroup-devops:latest


